{% set name = "pestpp" %}
{% set version = "5.2.7" %}
{% set sha256 = "e669a761e3472eef1e0a4ebf282720bfebf08e438dbc8c8d3491801a4559c027" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usgs/pestpp/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Removed-MD-to-MT-modification-for-MSVC.patch

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.9
    - make
    - ninja

test:
  commands:
    - test -f ${PREFIX}/bin/pestpp-da  # [unix]
    - test -f ${PREFIX}/bin/pestpp-glm  # [unix]
    - test -f ${PREFIX}/bin/pestpp-ies  # [unix]
    - test -f ${PREFIX}/bin/pestpp-mou  # [unix]
    - test -f ${PREFIX}/bin/pestpp-opt  # [unix]
    - test -f ${PREFIX}/bin/pestpp-sen  # [unix]
    - test -f ${PREFIX}/bin/pestpp-sqp  # [unix]
    - test -f ${PREFIX}/bin/pestpp-swp  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-da.exe  exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-glm.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-ies.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-mou.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-opt.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-sen.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-sqp.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\pestpp-swp.exe exit 1  # [win]

about:
  home: https://github.com/usgs/pestpp
  summary: A Software Suite for Parameter Estimation, Uncertainty Analysis, Management Optimization and Sensitivity Analysis
  description: |
    PEST++ is a software suite aimed at supporting complex numerical
    models in the decision-support context. Much focus has been devoted to
    supporting environmental models (groundwater, surface water, etc) but
    these tools are readily applicable to any computer model.
  license: CC0-1.0 AND MPL-2.0 AND BSD-3-Clause AND GPL-3.0-only AND LGPL-2.1-or-later AND Minpack AND EPL-2.0
  license_family: CC
  license_file:
    - USGS_disclaimer.txt
    - src/libs/Eigen/COPYING.BSD
    - src/libs/Eigen/COPYING.GPL
    - src/libs/Eigen/COPYING.LGPL
    - src/libs/Eigen/COPYING.MINPACK
    - src/libs/Eigen/COPYING.MPL2
    - src/libs/Eigen/COPYING.README
    - vendor-licenses/

extra:
  recipe-maintainers:
    - scharlton2
    - jdhughes-usgs
    - jtwhite79
    - mwtoews
